services:
  db.transaction:
    image: mysql:9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: transaction
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
volumes:
  mysql.transaction: